"""Reporter Agent — generates human-readable security report."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from jinja2 import Template

from scout.models import Finding

REPORT_TEMPLATE = """\
# Security Report — {{ project_name }}

**Scanned:** {{ scan_date }}
**Files scanned:** {{ files_scanned }}
**Total issues:** {{ total_issues }}

---

## Executive Summary

{% if critical > 0 -%}
**Your app has {{ critical }} critical vulnerabilit{{ "y" if critical == 1 else "ies" }}.** These must be fixed before shipping — they allow attackers to steal data, impersonate users, or take over your server.
{% elif high > 0 -%}
**{{ high }} high-severity issue{{ "s" if high > 1 else "" }} found.** Your app is at serious risk. Fix these in the next release.
{% elif medium > 0 -%}
**{{ medium }} medium-severity issue{{ "s" if medium > 1 else "" }} found.** Not immediately exploitable, but these weaken your security posture.
{% else -%}
**{{ low }} low-severity issue{{ "s" if low > 1 else "" }} found.** Minor improvements recommended but no urgent risk.
{% endif %}

| Severity | Count |
|----------|-------|
| 🔴 Critical | {{ critical }} |
| 🟠 High | {{ high }} |
| 🟡 Medium | {{ medium }} |
| 🔵 Low | {{ low }} |

---

## Fix Plan (Phased)

| Phase | What | Risk | Issues |
|-------|------|------|--------|
| 1 | Secrets, env vars, dependency bumps | Zero | {{ phase_counts.get(1, 0) }} |
| 2 | Security headers, CORS, rate limits | Low | {{ phase_counts.get(2, 0) }} |
| 3 | Auth & session fixes | Medium | {{ phase_counts.get(3, 0) }} |
| 4 | Injection & data layer | Medium-high | {{ phase_counts.get(4, 0) }} |
| 5 | Architecture changes | High | {{ phase_counts.get(5, 0) }} |

**How to apply:** Run `scout fix --phase 1` to start with zero-risk fixes.

---

## Issues

{% for finding in findings %}
### {{ loop.index }}. {{ severity_badge(finding.severity) }} {{ finding.title }}

**File:** `{{ finding.file }}:{{ finding.line }}`
**Phase:** {{ finding.fix_phase }} | **Scanner:** {{ finding.scanner }}

{{ finding.description }}

{% if finding.snippet %}
```
{{ finding.snippet }}
```
{% endif %}

**Fix:** {{ finding.fix_summary }}

---

{% endfor %}

## Next Steps

1. Review this report
2. Run `scout fix --phase 1` (zero-risk — secrets moved to .env, deps updated)
3. Test your app
4. Continue with `scout fix --phase 2` when ready
5. After fixes: `scout validate` to confirm issues are resolved

---

*Generated by [Scout](https://github.com/tejaswirajgit/Scout) — AI security team in a CLI.*
"""


def severity_badge(severity: str) -> str:
    """Return emoji badge for severity level."""
    return {
        "CRITICAL": "🔴",
        "HIGH": "🟠",
        "MEDIUM": "🟡",
        "LOW": "🔵",
    }.get(severity, "⚪")


def generate_report(
    findings: list[Finding],
    output_path: Path,
    project_path: Path | None = None,
) -> None:
    """Generate a Markdown security report from findings.

    Args:
        findings: List of findings from the Scout agent.
        output_path: Where to write the report.
        project_path: Root of the scanned project (for display).
    """
    project_name = project_path.name if project_path else "Unknown Project"

    # Count severities
    critical = sum(1 for f in findings if f.severity == "CRITICAL")
    high = sum(1 for f in findings if f.severity == "HIGH")
    medium = sum(1 for f in findings if f.severity == "MEDIUM")
    low = sum(1 for f in findings if f.severity == "LOW")

    # Count per phase
    phase_counts: dict[int, int] = {}
    for f in findings:
        phase_counts[f.fix_phase] = phase_counts.get(f.fix_phase, 0) + 1

    # Make relative file paths in findings
    for f in findings:
        if project_path:
            try:
                f.file = str(Path(f.file).relative_to(project_path))
            except ValueError:
                pass

    template = Template(REPORT_TEMPLATE)
    template.globals["severity_badge"] = severity_badge

    report = template.render(
        project_name=project_name,
        scan_date=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        files_scanned="—",
        total_issues=len(findings),
        critical=critical,
        high=high,
        medium=medium,
        low=low,
        phase_counts=phase_counts,
        findings=findings,
    )

    output_path.write_text(report, encoding="utf-8")
